#!/bin/bash


spidroin="GTGGATATGGAGGTCTTGGTGGACAAGGTGCCGGACAAGGAGCTGGTGCAGCCGCCGCAGCAGCAGCTGG
TGGTGCCGGACAAGGAGGATATGGAGGTCTTGGAAGCCAAGGTGCTGGACGAGGTGGACAAGGTGCAGGC
GCAGCCGCAGCCGCAGCTGGAGGTGCTGGTCAAGGAGGATACGGAGGTCTTGGAAGCCAAGGTGCTGGAC
GAGGAGGATTAGGTGGACAAGGTGCAGGTGCAGCAGCAGCAGCTGGAGGTGTCGGACAAGGAGGACTAGG
TGGACAAGGTGCTGGACAAGGAGCTGGAGCAGCTGCTGCAGCAGCTGGTGGTGCCGGACAAGGAGGATAT
GGAGGTCTCGGAAGCCAAGGTGCAGGACGAGGTGGATCAGGTGGACAAGGGGCAGGTGCAGCAGCAGCAG
CAGCTGGAGGTGCCGGACAAGGAGGATATGGAGGTCTTGGAAGCCAAGGTGCAGGACGAGGTGGATTAGG
TGGACAGGGTGCAGGTGCAGCAGCAGCAGCAGCAGCCGGAGGTGCTGGACAAGGAGGATACGGTGGTCTT
GGTGGACAAGGTGCCGGACAAGGTGGCTATGGAGGACTTGGAAGCCAAGGTGCTGGACGAGGAGGATTAG
GTGGACAAGGTGCAGGTGCAGCAGCAGCAGCTGGAGGTGCCGGACAAGGAGGACTAGGTGGACAAGGAGC
TGGAGCAGCCGCTGCAGCAGCTGGTGGTGCCGGACAAGGAGGATATGGAGGTCTTGGAAGCCAAGGTGCT
GGACGAGGTGGACAAGGTGCAGGCGCAGCCGCAGCAGCAGCCGGAGGTGCTGGACAAGGAGGATACGGTG
GACAAGGTGCCGGACAAGGAGGCTATGGAGGACTTGGAAGCCAAGGTGCTGGACGAGGAGGATTAGGTGG
ACAAGGTGCAGGTGCAGCAGCAGCAGCAGCAGCAGCTGGAGGTGCCGGACAAGGAGGATTAGGTGGACAA
GGTGCAGGTGCAGCAGCAGCAGCAGCTGGAGGTGCTGGACAAGGAGGATTAGGTGGACAAGGTGCTGGAC
AAGGAGCTGGAGCAGCCGCTGCAGCAGCCGCTGCAGCAGCTGGTGGTGTTAGACAAGGAGGATATGGAGG
TCTTGGAAGCCAAGGTGCTGGACGAGGTGGACAAGGTGCAGGCGCAGCCGCAGCAGCAGCCGGAGGTGCT
GGACAAGGAGGATATGGTGGTCTTGGTGGACAAGGTGTTGGACGAGGTGGATTAGGTGGACAAGGTGCAG
GCGCAGCGGCAGCTGTTGGTGCTGGACAAGGAGGATATGGTGGTGTTGGTTCTGGGGCGTCTGCTGCCTC
TGCAGCTGCATCCCGTTTGTCTTCTCCTCAAGCTAGTTCAAGAGTTTCATCAGCTGTTTCCAACTTGGTT
GCAAGTGGTCCTACTAATTCTGCGGCCTTGTCAAGTACAATCAGTAATGTGGTTTCACAAATAGGCGCCA
GCAATCCTGGTCTTTCTGGATGTGATGTCCTCATTCAAGCTCTTCTCGAGGTTGTTTCTGCTCTTATCCA
GATCTTAGGTTCTTCCAGCATCGGCCAAGTTAACTATGGTTCCGCTGGACAAGCCACTCAGATCGTTGGT
CAATCAGTTTATCAAGCCCTAGGTTAAATGTAAAATCAAGAGTTGCTAAAACTTAATGAATCGGGCTGTT
AAATTTGTGTTAGTTTTAAAATATTTTCAATAAATATTATGCATAT"


# Count occurrences of each nucleotide
A=$(echo "$spidroin" | grep -o "A" | wc -l)
G=$(echo "$spidroin" | grep -o "G" | wc -l)
C=$(echo "$spidroin" | grep -o "C" | wc -l)
T=$(echo "$spidroin" | grep -o "T" | wc -l)


# Print the counts of each nucleotide
echo "Adenine is $A"
echo "Guanine is $G"
echo "Cytosine is $C"
echo "Thymine is $T"


# Calculate and print the total number of GC pairs
GC=$((G + C))
echo "Total number of GC pairs: $GC"


# Calculate and print the total number of nucleotides
total=$((A + G + C + T))
echo "Total number of nucleotides: $total"


# Calculate and print the percentage of GC pairs
percentage=$(echo "scale=2; $GC / $total * 100" | bc)
echo "Percentage of GC pairs: $percentage"



